{% set version = "0.4.6" %}

package:
  name: cons
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cons/cons-{{ version }}.tar.gz
  sha256: 669fe9d5ee916d5e42b9cac6acc911df803d04f2e945c1604982a04d27a29b47

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - logical-unification >=0.4.0

test:
  imports:
    - cons
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pythological/python-cons
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An implementation of Lisp/Scheme-like cons in Python.
  description: |
    The cons package attempts to emulate the semantics of Lisp/Scheme's cons as closely as possible while
    incorporating all the built-in Python sequence types.
  dev_url: https://github.com/pythological/python-cons
  doc_url: https://github.com/pythological/python-cons

extra:
  recipe-maintainers:
    - brandonwillard
